# Generated by Django 3.2.13 on 2023-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.CharField(max_length=100)),
                ('test_input', models.TextField()),
                ('test_output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usercode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_code', models.TextField()),
            ],
        ),
    ]
