# Generated by Django 3.2.13 on 2023-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='problem_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
