# Generated by Django 3.2.18 on 2023-04-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
