# Generated by Django 3.2.18 on 2023-04-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumbnail_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_img',
        ),
    ]
